#!/bin/sh

if [ ! -d .git ]; then
    echo "must be run from root of advent-of-code repository" >&2
    exit 1
fi

if [ ! -f ".env" ]; then
	echo ".env does not exist."
	exit 1
fi
source .env
if [ ! -n "$KEY" ]; then
	echo ".env file doesn't contain KEY=<key>."
	exit 1
fi

YEAR=$(date +%Y)
DAY=$(if [ $# != 1 ]; then date +%-d; else echo $1; fi)
NAME="$(printf "day%02d" "$DAY")"

if [ -d $NAME ]; then
    echo "$NAME already exists -- stopping." >&2
    exit 1
fi

cargo new --bin "$NAME"
mkdir "$NAME/input"
cp boilerplate.rs "$NAME/src/main.rs"

echo "Downloading puzzle input for $YEAR, day $DAY..."
URL="https://adventofcode.com/$YEAR/day/$DAY/input"
curl -A "Private script by endden@gmail.com" --cookie "session=$KEY" $URL >"$NAME/input/input.txt"